# Direções inspiradas em estilos do awesome-design-md (tokens tirados de cada DESIGN.md e adaptados ao app).
def extras(COMMON, GEIST):
    F = dict(COMMON, W_DISPLAY="300", W_DISPLAY_SUB="300", W_TITLE="400", W_NAME="500",
      FONTS_LINK="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@300;400;500;600&amp;family=Geist+Mono:wght@400;500&amp;display=swap",
      UI="'Hanken Grotesk', system-ui, -apple-system, sans-serif", DISPLAY="'Hanken Grotesk', system-ui, -apple-system, sans-serif", DISPLAY_TRACK="-0.025em",
      BG="#F6F9FC", PANEL="#FFFFFF", ELEVATED="#F6F9FC", BORDER="#E3E8EE", TEXT="#0D253D", TEXT2="#425466", TEXT3="#64748D",
      ACCENT="#533AFD", ACCENT_HOVER="#4434D4", ACCENT_TINT="rgba(83,58,253,0.10)", ACCENT_TEXT_ON_LIGHT="#533AFD", LINK="#533AFD",
      GREEN="#0E7A45", GREEN_TINT="rgba(14,122,69,0.12)", AMBER="#B25E0A", AMBER_TINT="rgba(178,94,10,0.12)",
      RED="#C0224F", RED_TINT="rgba(234,34,97,0.10)", RED_BORDER="rgba(234,34,97,0.4)", RED_ROW="rgba(234,34,97,0.04)",
      R_PANEL="12px", R_CTRL="6px", R_BTN="999px", R_SEG_IN="999px", BADGE_R="999px", AVATAR_R="50%", MARK_R="12", MARK_BG="#533AFD", MARK_FG="#FFFFFF",
      PANEL_BORDER="#E3E8EE", PANEL_SHADOW="0 1px 3px rgba(0,55,112,0.08)", SEP="#E3E8EE",
      FIELD_BG="#FFFFFF", FIELD_BORDER="#E3E8EE",
      SEG_TRACK="#F6F9FC", SEG_TRACK_BORDER="#E3E8EE", SEG_ACTIVE_BG="#FFFFFF", SEG_ACTIVE_TEXT="#0D253D", SEG_ACTIVE_BORDER="#E3E8EE", SEG_ACTIVE_SHADOW="0 1px 3px rgba(0,55,112,0.10)",
      BTN1_BG="#533AFD", BTN1_TEXT="#FFFFFF", BTN2_BG="#FFFFFF", BTN2_TEXT="#533AFD", BTN2_BORDER="#533AFD",
      TOGGLE_ON="#533AFD", SEG_PAID="#0D253D", SEG_NEXT="rgba(83,58,253,0.16)", SEG_TODO="#E3E8EE", RING_TRACK="#E3E8EE",
      BUBBLE_BG="#F6F9FC", BUBBLE_BORDER="#E3E8EE",
      HERO_BG="linear-gradient(100deg, rgba(245,233,212,0.85), rgba(230,224,245,0.7) 45%, rgba(83,58,253,0.08) 80%, rgba(234,34,97,0.08))",
      LABEL="Direção F · Inspirada na Stripe", DESC="Tipografia fina (peso 300) com tracking negativo, índigo em pílula como única ação, painéis brancos com sombra leve e um degradê suave no balanço. Hanken Grotesk faz o papel da Söhne.",
      NOTE_ACOES="Pílulas em tudo. Secundário é contorno índigo, nunca preenchido: uma ação preenchida por bloco.",
      NOTE_CAMPOS="Cantos de 6px nos campos, sombra em vez de borda forte. Números tabulares sempre.",
      NOTE_CLIENTE="Selos em pílula com o mesmo tom fino. O balão usa o azul-gelo do fundo.",
      MOTIVO="Cara de infraestrutura financeira séria: leve, precisa, com o número em fonte fina que parece impressa.",
      CONTRA="Peso 300 pede tela boa e tamanho grande; em celular barato o texto fino some. O índigo é vizinho do violeta da B.")

    G = dict(COMMON, W_DISPLAY="600", W_DISPLAY_SUB="500", W_TITLE="600", W_NAME="500",
      FONTS_LINK="https://fonts.googleapis.com/css2?"+GEIST+"&amp;display=swap",
      DISPLAY="'Geist', system-ui, -apple-system, sans-serif", DISPLAY_TRACK="-0.05em",
      BG="#FAFAFA", PANEL="#FFFFFF", ELEVATED="#F5F5F5", BORDER="#EBEBEB", TEXT="#171717", TEXT2="#4D4D4D", TEXT3="#888888",
      ACCENT="#0070F3", ACCENT_HOVER="#0761D1", ACCENT_TINT="rgba(0,112,243,0.10)", ACCENT_TEXT_ON_LIGHT="#0070F3", LINK="#0070F3",
      GREEN="#0F8A3C", GREEN_TINT="rgba(15,138,60,0.12)", AMBER="#A36A00", AMBER_TINT="rgba(245,166,35,0.16)",
      RED="#E00000", RED_TINT="rgba(238,0,0,0.08)", RED_BORDER="rgba(238,0,0,0.35)", RED_ROW="rgba(238,0,0,0.04)",
      R_PANEL="8px", R_CTRL="6px", R_BTN="999px", R_SEG_IN="999px", BADGE_R="999px", AVATAR_R="50%", MARK_R="10", MARK_BG="#171717", MARK_FG="#FFFFFF",
      PANEL_BORDER="#EBEBEB", PANEL_SHADOW="0 1px 1px rgba(0,0,0,0.04), 0 2px 2px rgba(0,0,0,0.06)", SEP="#EBEBEB",
      FIELD_BG="#FFFFFF", FIELD_BORDER="#EBEBEB",
      SEG_TRACK="#FAFAFA", SEG_TRACK_BORDER="#EBEBEB", SEG_ACTIVE_BG="#171717", SEG_ACTIVE_TEXT="#FFFFFF", SEG_ACTIVE_BORDER="#171717", SEG_ACTIVE_SHADOW="none",
      BTN1_BG="#171717", BTN1_TEXT="#FFFFFF", BTN2_BG="#FFFFFF", BTN2_TEXT="#171717", BTN2_BORDER="#EBEBEB",
      TOGGLE_ON="#171717", SEG_PAID="#171717", SEG_NEXT="rgba(0,112,243,0.16)", SEG_TODO="#EBEBEB", RING_TRACK="#EBEBEB",
      BUBBLE_BG="#FAFAFA", BUBBLE_BORDER="#EBEBEB",
      HERO_BG="linear-gradient(90deg, rgba(0,124,240,0.10), rgba(0,223,216,0.10) 30%, rgba(121,40,202,0.07) 60%, rgba(255,0,128,0.07) 80%, rgba(249,203,40,0.10))",
      LABEL="Direção G · Inspirada na Vercel", DESC="Preto e branco com precisão: Geist e Geist Mono (as fontes que o projeto já tem), tracking bem negativo, pílula preta como ação, sombras empilhadas bem leves e um degradê só no balanço.",
      NOTE_ACOES="Pílula preta na ação principal, branca com borda na secundária, azul só em texto. Segmentado com o item ativo preto.",
      NOTE_CAMPOS="Campos de 6px com borda hairline, 40px de altura. Rótulos técnicos em mono.",
      NOTE_CLIENTE="Selos em pílula cinza-claro. Balão quase sem cor: a mensagem é o destaque.",
      MOTIVO="Custo zero de fonte e cara de ferramenta de desenvolvedor. O preto puro faz o azul e os status gritarem quando aparecem.",
      CONTRA="Monocromático demais pode soar frio para quem empresta a conhecidos. O degradê precisa de moderação para não virar clichê.")

    H = dict(COMMON, W_DISPLAY="600", W_DISPLAY_SUB="500", W_TITLE="600", W_NAME="500",
      FONTS_LINK="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,500..600&amp;"+GEIST+"&amp;display=swap",
      DISPLAY="'Newsreader', Georgia, 'Times New Roman', serif", DISPLAY_TRACK="-0.01em",
      BG="#FBFBFA", PANEL="#FFFFFF", ELEVATED="#F6F5F4", BORDER="#E5E3DF", TEXT="#37352F", TEXT2="#6B6A66", TEXT3="#9B9A97",
      ACCENT="#2383E2", ACCENT_HOVER="#0075DE", ACCENT_TINT="#DCECFA", ACCENT_TEXT_ON_LIGHT="#0B6BC2", LINK="#0075DE",
      GREEN="#157A33", GREEN_TINT="#D9F3E1", AMBER="#B04800", AMBER_TINT="#FFE8D4",
      RED="#C92A2A", RED_TINT="#FDE0EC", RED_BORDER="rgba(224,49,49,0.4)", RED_ROW="rgba(224,49,49,0.04)",
      R_PANEL="12px", R_CTRL="8px", R_BTN="8px", R_SEG_IN="6px", BADGE_R="6px", AVATAR_R="8px", MARK_R="10", MARK_BG="#37352F", MARK_FG="#FFFFFF",
      PANEL_BORDER="#E5E3DF", PANEL_SHADOW="0 1px 2px rgba(15,15,15,0.04)", SEP="#E5E3DF",
      FIELD_BG="#FFFFFF", FIELD_BORDER="#C8C4BE",
      SEG_TRACK="#F6F5F4", SEG_TRACK_BORDER="rgba(0,0,0,0)", SEG_ACTIVE_BG="#FFFFFF", SEG_ACTIVE_TEXT="#37352F", SEG_ACTIVE_BORDER="#E5E3DF", SEG_ACTIVE_SHADOW="0 1px 2px rgba(15,15,15,0.06)",
      BTN1_BG="#37352F", BTN1_TEXT="#FFFFFF", BTN2_BG="#FFFFFF", BTN2_TEXT="#37352F", BTN2_BORDER="#C8C4BE",
      TOGGLE_ON="#2383E2", SEG_PAID="#37352F", SEG_NEXT="#DCECFA", SEG_TODO="#E5E3DF", RING_TRACK="#E5E3DF",
      BUBBLE_BG="#F6F5F4", BUBBLE_BORDER="#E5E3DF",
      HERO_BG="linear-gradient(#FFE8D4, #FFE8D4)",
      LABEL="Direção H · Inspirada na Notion", DESC="Minimalismo quente: texto carvão, serifa nos títulos e números (Newsreader), botões retangulares de 8px em carvão, chips com fundos pastel e o painel de balanço em pêssego. Azul só em link e foco.",
      NOTE_ACOES="Botões retangulares, nunca pílula. Carvão na ação principal; o azul fica para links e para o interruptor.",
      NOTE_CAMPOS="Campos com borda bege e cantos de 8px. A prévia do cálculo usa o azul-céu pastel.",
      NOTE_CLIENTE="Chips pastel de 6px (menta, pêssego, rosa, céu) em vez de pílulas. Balão na superfície bege.",
      MOTIVO="Parece um caderno de anotações bem cuidado: acolhedor e legível, sem cara de banco nem de painel técnico.",
      CONTRA="Serifa em número grande é bonita, mas o resto precisa ficar muito simples para não virar blog. Pastel pede cuidado com contraste.")

    I = dict(COMMON, W_DISPLAY="900", W_DISPLAY_SUB="700", W_TITLE="800", W_NAME="600",
      FONTS_LINK="https://fonts.googleapis.com/css2?family=Onest:wght@700;800;900&amp;"+GEIST+"&amp;display=swap",
      DISPLAY="'Onest', system-ui, -apple-system, sans-serif", DISPLAY_TRACK="-0.03em",
      BG="#E8EBE6", PANEL="#FFFFFF", ELEVATED="#E8EBE6", BORDER="#0E0F0C", TEXT="#0E0F0C", TEXT2="#454745", TEXT3="#868685",
      ACCENT="#9FE870", ACCENT_HOVER="#CDFFAD", ACCENT_TINT="rgba(159,232,112,0.35)", ACCENT_TEXT_ON_LIGHT="#163300", LINK="#163300",
      GREEN="#1E8A3B", GREEN_TINT="rgba(46,173,75,0.14)", AMBER="#8A6D00", AMBER_TINT="rgba(255,209,26,0.28)",
      RED="#D03238", RED_TINT="rgba(208,50,56,0.10)", RED_BORDER="rgba(208,50,56,0.4)", RED_ROW="rgba(208,50,56,0.05)",
      R_PANEL="24px", R_CTRL="12px", R_BTN="24px", R_SEG_IN="20px", BADGE_R="999px", AVATAR_R="50%", MARK_R="16", MARK_BG="#9FE870", MARK_FG="#163300",
      PANEL_BORDER="rgba(0,0,0,0)", PANEL_SHADOW="none", SEP="#E8EBE6",
      FIELD_BG="#FFFFFF", FIELD_BORDER="#0E0F0C",
      SEG_TRACK="#E8EBE6", SEG_TRACK_BORDER="rgba(0,0,0,0)", SEG_ACTIVE_BG="#0E0F0C", SEG_ACTIVE_TEXT="#FFFFFF", SEG_ACTIVE_BORDER="#0E0F0C", SEG_ACTIVE_SHADOW="none",
      BTN1_BG="#9FE870", BTN1_TEXT="#163300", BTN2_BG="#E8EBE6", BTN2_TEXT="#0E0F0C", BTN2_BORDER="rgba(0,0,0,0)",
      TOGGLE_ON="#163300", SEG_PAID="#163300", SEG_NEXT="rgba(159,232,112,0.55)", SEG_TODO="#E8EBE6", RING_TRACK="#E8EBE6",
      BUBBLE_BG="#E2F6D5", BUBBLE_BORDER="rgba(0,0,0,0)",
      HERO_BG="none",
      LABEL="Direção I · Inspirada na Wise", DESC="Fundo sálvia, cartões brancos de 24px sem borda nem sombra, verde-limão como ação com texto verde-escuro, tipografia pesada (Onest 900) e campos com contorno preto de 1px.",
      NOTE_ACOES="Limão só na ação principal; secundário é sálvia, sem borda. Segmentado com o item ativo preto.",
      NOTE_CAMPOS="Campos com contorno preto de 1px e cantos de 12px: parecem formulário de papel. Foco ganha halo limão.",
      NOTE_CLIENTE="Selos em pílula com verde-escuro para pago (o limão fica reservado para ação). Balão verde-pálido.",
      MOTIVO="Amigável e direto, com cara de dinheiro sem cara de banco. As formas grandes funcionam muito bem no celular.",
      CONTRA="Verde é a cor do Jurex; aqui é um limão bem diferente, mas ainda é verde. Peso 900 em número grande domina a tela.")

    J = dict(COMMON, W_DISPLAY="600", W_DISPLAY_SUB="500", W_TITLE="500", W_NAME="500",
      FONTS_LINK="https://fonts.googleapis.com/css2?"+GEIST+"&amp;display=swap",
      DISPLAY="'Geist', system-ui, -apple-system, sans-serif", DISPLAY_TRACK="-0.04em",
      BG="#F7F8F8", PANEL="#FFFFFF", ELEVATED="#F1F2F4", BORDER="#E4E5E8", TEXT="#1C1D1F", TEXT2="#5C5E63", TEXT3="#8A8F98",
      ACCENT="#5E6AD2", ACCENT_HOVER="#4F5ABF", ACCENT_TINT="rgba(94,106,210,0.12)", ACCENT_TEXT_ON_LIGHT="#4F5ABF", LINK="#4F5ABF",
      GREEN="#1F8A39", GREEN_TINT="rgba(39,166,68,0.12)", AMBER="#B26B00", AMBER_TINT="rgba(240,160,0,0.14)",
      RED="#C53030", RED_TINT="rgba(197,48,48,0.10)", RED_BORDER="rgba(197,48,48,0.35)", RED_ROW="rgba(197,48,48,0.04)",
      R_PANEL="12px", R_CTRL="8px", R_BTN="8px", R_SEG_IN="6px", BADGE_R="4px", AVATAR_R="6px", MARK_R="10", MARK_BG="#5E6AD2", MARK_FG="#FFFFFF",
      PANEL_BORDER="#E4E5E8", PANEL_SHADOW="none", SEP="#ECEEF0",
      FIELD_BG="#FFFFFF", FIELD_BORDER="#E4E5E8",
      SEG_TRACK="#F1F2F4", SEG_TRACK_BORDER="rgba(0,0,0,0)", SEG_ACTIVE_BG="#FFFFFF", SEG_ACTIVE_TEXT="#1C1D1F", SEG_ACTIVE_BORDER="#E4E5E8", SEG_ACTIVE_SHADOW="0 1px 2px rgba(0,0,0,0.06)",
      BTN1_BG="#5E6AD2", BTN1_TEXT="#FFFFFF", BTN2_BG="#FFFFFF", BTN2_TEXT="#1C1D1F", BTN2_BORDER="#E4E5E8",
      TOGGLE_ON="#5E6AD2", SEG_PAID="#1C1D1F", SEG_NEXT="rgba(94,106,210,0.18)", SEG_TODO="#E4E5E8", RING_TRACK="#E4E5E8",
      BUBBLE_BG="#F7F8F8", BUBBLE_BORDER="#E4E5E8",
      HERO_BG="none",
      LABEL="Direção J · Inspirada na Linear (versão clara)", DESC="A Linear é escura por padrão; esta é a adaptação clara: escada de superfícies em vez de sombra, azul-lavanda só em ação e foco, chips retos de 4px, tracking apertado, tudo em Geist.",
      NOTE_ACOES="Botões de 8px, peso 500, sem pílula. Lavanda só na ação principal e no interruptor.",
      NOTE_CAMPOS="Campos discretos com borda hairline. O foco é um anel lavanda a 50%, como no app da Linear.",
      NOTE_CLIENTE="Chips de 4px quase retos, sem ponto colorido grande. Densidade alta, nada de decoração.",
      MOTIVO="Precisão e densidade: muita informação sem ruído. É o padrão que desenvolvedor reconhece como ferramenta séria.",
      CONTRA="Muito parecida com a B; a diferença é de temperatura e detalhe (chips retos, superfícies em escada). Pode soar fria para o público.")
    return dict(DirecaoF=F, DirecaoG=G, DirecaoH=H, DirecaoI=I, DirecaoJ=J)
